apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager-rest
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9999"
spec:
  type: NodePort
  ports:
  - name: rest
    port: 8081
    targetPort: 8081
    nodePort: 30081
  - name: metrics
    port: 9999
    targetPort: 9999
    nodePort: 30082
  selector:
    app: flink
    component: jobmanager
